version: '3.8'

services:
  backend:
    image: ovittormachado/rangos-server-app
    environment:
      PORT: 3000
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      REFRESH_SECRET: jwt_refresh_secret_default
      EMAIL_USER: jwt_email_user_default
      EMAIL_PASS: jwt_email_pass_default
      APP_URL: https://rangos-back-end-production.up.railway.app
      STORAGE_TYPE: s3
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: us-east-2
      AWS_BUCKET_NAME: bucket.rangos
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: railway

    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
